import type { IconType } from "@/entities/vault";
import type { IoniconsName } from "@/shared/lib/iconTypes";

export const ICON_COLORS = [
  "#2563EB",
  "#10B981",
  "#8B5CF6",
  "#F59E0B",
  "#EF4444",
  "#EC4899",
  "#06B6D4",
  "#6B7280",
  "#1E3A5F",
  "#065F46",
  "#4C1D95",
  "#92400E",
];

export const EMOJI_GROUPS = [
  {
    labelKey: "vault.icon_group_finance",
    emojis: [
      "🏦",
      "💳",
      "💰",
      "🏧",
      "💵",
      "📊",
      "💹",
      "🏪",
      "🧾",
      "💴",
      "💶",
      "💷",
    ],
  },
  {
    labelKey: "vault.icon_group_social",
    emojis: [
      "💬",
      "📸",
      "🎵",
      "▶️",
      "🐦",
      "📱",
      "🌐",
      "📧",
      "📞",
      "🎮",
      "🎬",
      "📺",
    ],
  },
  {
    labelKey: "vault.icon_group_security",
    emojis: [
      "🔐",
      "🔑",
      "🛡️",
      "🔒",
      "🗝️",
      "🔓",
      "🛂",
      "🪪",
      "📋",
      "🗃️",
      "📁",
      "🗄️",
    ],
  },
  {
    labelKey: "vault.icon_group_shopping",
    emojis: [
      "🛍️",
      "🛒",
      "🏬",
      "🎁",
      "🏷️",
      "📦",
      "🚚",
      "🧺",
      "🛺",
      "🏪",
      "🧃",
      "🍔",
    ],
  },
  {
    labelKey: "vault.icon_group_other",
    emojis: [
      "💼",
      "🏠",
      "🚗",
      "✈️",
      "🎓",
      "💊",
      "🔧",
      "⚙️",
      "🌟",
      "❤️",
      "🎯",
      "🧩",
    ],
  },
];

export const IONICON_GROUPS: { labelKey: string; icons: IoniconsName[] }[] = [
  {
    labelKey: "vault.icon_group_finance",
    icons: [
      "card-outline",
      "cash-outline",
      "wallet-outline",
      "trending-up-outline",
      "bar-chart-outline",
      "stats-chart-outline",
    ],
  },
  {
    labelKey: "vault.icon_group_communication",
    icons: [
      "mail-outline",
      "chatbubble-outline",
      "call-outline",
      "videocam-outline",
      "megaphone-outline",
      "notifications-outline",
    ],
  },
  {
    labelKey: "vault.icon_group_security",
    icons: [
      "shield-outline",
      "lock-closed-outline",
      "key-outline",
      "finger-print-outline",
      "eye-outline",
      "alert-circle-outline",
    ],
  },
  {
    labelKey: "vault.icon_group_general",
    icons: [
      "home-outline",
      "car-outline",
      "airplane-outline",
      "school-outline",
      "briefcase-outline",
      "globe-outline",
    ],
  },
];
